### ISSUE TITLE
DAW can not load ChowCentaur.so

### ISSUE THREAD

**Issue by ct2034** [jatinchowdhury18/KlonCentaur#7]
I built the plugin on Ubuntu 20.04.1 according to the readme.
Then I copied the library file to my ~/.vst folder. 
But both Ardour and Reaper can not load the plugin. Reaper even puts it into the list of plugins that failed to load but gives no explanation on why it failed.

**Comment by jatinchowdhury18** [comment]
Hi @ct2034,

Thanks for the report! Unfortunately, the VST target is not built by default when building from source, since the Steinberg is no longer distributing the VST2 SDK. If VST3 works for you, the VST3 build can be found after building, at `build/ChowCentaur/ChowCentaur_artefacts/VST3/ChowCentaur.vst3` (this path might change a little bit if you're using a different CMake generator). Since the .vst3 path is actuall a directory, be sure to copy the full directory to your VST3 path!

Alternatively, you can still build the VST from source, but you need to use the following steps:
1. Acquire the VST2 SDK. I am not allowed to distribute the SDK with my source code because of Steinberg's rules, but you may be able to find the SDK somewhere, or you may already have it.
2. Set the VST SDK path in `CMakeLists.txt`: Change line 14 to `juce_set_vst2_sdk_path(/path/to/vst2_sdk/)`.
3. Enable VST target: in `ChowCentaur/CMakeLists.txt`, change line 5 to `FORMATS AU VST3 Standalone AUv3 VST`, so that `VST` is no longer commented out.
4. Build with CMake as usual.
5. The VST build should be found at `build/ChowCentaur/ChowCentaur_artefacts/VST/ChowCentaur.so`.

I also plan to get LV2 support working in the future, but it might take me a little more time. I hope this information helps. Please let me know if you run into any issues!

Thanks,
Jatin

**Comment by ct2034** [comment]
Thanks for that. I guess the library i copied was the standalone version. When I copied the whole vst3 folder, all worked!
